project:
  type: book
  output-dir: docs

book:
  title: "AOMS5 Workshop - Modelling Behaviour with Mixed Effects"
  author: "Jack E. Taylor"
  date: "07/02/2026"
  chapters:
    - index.qmd
    - 01-linear_models.qmd
    - 02-random_intercepts.qmd
    - 03-random_slopes.qmd
    - 04-random_correlatons.qmd
    - 05-power_analyses.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly
    knitr:
      opts_chunk:
        dev: png
        dev.args: 
          type: cairo-png

filters:
  - collapse-output  # https://github.com/mcanouil/quarto-collapse-output
